### PR TITLE
Not consider extra fields.

### PR DESCRIPTION
**Pull request by frodsan**

### CODE REVIEW

**Comment by frodsan** [comment]
Closed in favor of `attributes` branch.

**Comment by filipegiusti** [comment]
May I ask what was the reasoning for this change?

**Comment by soveran** [comment]
@filipegiusti It was a result of a survey among several users. It turned out for most people the old behavior made things more difficult: raising an exception when extra fields were sent was pushing them to put workarounds in place. Does this change break something for you? We can always revisit design decisions.

**Comment by filipegiusti** [comment]
My use case is an API. I was using the exception to let API clients know what they are doing wrong. I could keep it if there is an easy way to get the ignored attributes and/or assert empty for ignored attributes.

**Pull request merged**
